# Generated by Django 5.2.4 on 2025-07-29 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai/')),
                ('data_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BL', 'Black Tea'), ('ML', 'Masala Chai'), ('GR', 'Green Tea'), ('EL', 'Elaichi Chai'), ('AD', 'Adrak Chai')], max_length=2)),
            ],
        ),
    ]
